# -*- coding: utf-8 -*-
"""penjumlahan.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14G4mHJuLVE9EAYRdVz-neJ5MPawAT6rK
"""

def penjumlahan (angka_1 , angka_2):
    jumlah = angka_1 + angka_2
    return jumlah